Repository Lightning-AI/ecosystem-ci, pull requests merged in 2022-01, with the labels that each got.

#21 Dockers for GPU testing
  .github/workflows/dockers.yml
  actions/Dockerfile
Labels: enhancement, CI/CD

#7 Add NeMo
  .azure/testing-template.yml
  configs/NVIDIA/nemo-release.yaml
  requirements.txt
Labels: New project

#29 Add DeepSpeech.pytorch
  .github/CODEOWNERS
  configs/SeanNaren/deepspeech-release.yaml
Labels: New project

#27 add Solo-learn
  configs/vturrisi/solo-learn_pl-develop.yaml
  configs/vturrisi/solo-learn_pl-release.yaml
Labels: New project

#26 Update Flash to test `image,tabular,text` extras
  configs/PyTorchLightning/flash_pl-develop.yaml
  configs/PyTorchLightning/flash_pl-release.yaml
Labels: enhancement

#34 docs: add engagement rules
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: documentation
