Repository Lightning-AI/ecosystem-ci, pull requests merged in 2022-12, with the labels that each got.

#73 Neptune client tests moved to tests subdirectory
  configs/neptune-ai/lightning_integration.yaml
Labels: enhancement

#75 allow install's flags
  .github/workflows/ci_test-acts.yml
  .github/workflows/ci_testing.yml
  actions/_config.yaml
  actions/assistant.py
Labels: enhancement

#76 switch to stable & fix CI matrix
  .github/workflows/ci_test-acts.yml
  .github/workflows/ci_testing.yml
  actions/assistant.py
  configs/Lightning-AI/bolts_pl-release.yaml
  configs/Lightning-AI/flash_pl-release.yaml
  configs/Lightning-AI/metrics_pl-release.yaml
  configs/Lightning-AI/transformers_pl-release.yaml
  configs/NVIDIA/nemo-release.yaml
  configs/SeanNaren/deepspeech-release.yaml
  configs/microsoft/deepspeed-release.yaml
  configs/neptune-ai/lightning_integration.yaml
  configs/vturrisi/solo-learn_pl-release.yaml
Labels: bug / fix

#81 CI: use LitPool
  .azure/testing-template.yml
  configs/Lightning-AI/metrics_pl-release.yaml
  configs/neptune-ai/lightning_integration.yaml
Labels: CI/CD

#82 add TM & bolts to solo-learn
  configs/vturrisi/solo-learn_lit-develop.yaml
  configs/vturrisi/solo-learn_lit-release.yaml
Labels: bug / fix
